# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Tie-Sub
version:      0.03
version_from: lib/Tie/Sub.pm
installdirs:  site
requires:
    Test::Simple:                  0.46

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
