---
name: Tie-Sub
version: 0.07
author:
  - 'Steffen Winkler <steffenw at cpan.org>'
abstract: 'Tie::Sub - Tying a subroutine, function or method to a hash'
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Params::Validate: 0
build_requires:
  Test::Simple: 0
recommends:
  Test::More: 0
  Test::Pod: 1.14
  Test::Pod::Coverage: 1.04
provides:
  Tie::Sub:
    file: lib/Tie/Sub.pm
    version: 0.07
generated_by: Module::Build version 0.33
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
