---
abstract: 'Tie::Sub - Tying a subroutine, function or method to a hash'
author:
  - 'Steffen Winkler <steffenw at cpan.org>'
build_requires:
  Cwd: 0
  Test::Differences: 0.60
  Test::Exception: 0
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tie-Sub
provides:
  Tie::Sub:
    file: lib/Tie/Sub.pm
    version: 1.001
recommends:
  Test::Pod: 1.14
  Test::Pod::Coverage: 1.04
requires:
  Carp: 0
  English: 0
  Params::Validate: 0
  perl: 5.006
resources:
  license: http://dev.perl.org/licenses/
version: 1.001
